### ISSUE TITLE
Works in debug mode but does not work in release mode

### ISSUE THREAD

**Issue by musabibnusiraj** [SrilalS/Payhere-Flutter-Plugin#1]
**Sandbox**
The error occurs by app-release.apk

When I click Visa or something. It's closed. 
and response like below.

 _{"STATUS": "ERROR" ,"code": -1}_

On Debug mode. it's working fine. (USB through run-app)

**Comment by SrilalS** [comment]
Any Logs or any output?
have you added the Internet Permissions?  (<uses-permission android:name="android.permission.INTERNET" />)
Have Just ran the flutter buid apk without adding a Release Mode or its a proper release mode?

**Comment by musabibnusiraj** [comment]
I used Internet Permissions.
`<uses-permission android:name="android.permission.INTERNET" />`

I clone from this repo. so the same code.

I ran `flutter build apk`

_Payhere-Flutter-Plugin\example\build\app\outputs\flutter-apk\app-release.apk_

I installed this build APK file.

![image](https://user-images.githubusercontent.com/47845204/92510512-9a07ba00-f229-11ea-8872-d44c1e2a98fe.png)

The above screen opens then I choose one method.
after that suddenly the screen closed.

response-text
{"STATUS": "ERROR" ,"code": -1}
![f142ef38-de54-4aec-b741-95447c125a20](https://user-images.githubusercontent.com/47845204/92514287-44cea700-f22f-11ea-8703-9a71f321df52.jpg)


but works fine while debugging.
 The below screen shows on debug mode

![image](https://user-images.githubusercontent.com/47845204/92511216-a6d8dd80-f22a-11ea-9224-964a6238a2b3.png)


is this error occur because of the sandbox?

or the error occurs from any other reasons?

I tried payhere_flutter. They're also the same issue.

**Comment by SrilalS** [comment]
There is a Bug of setting it to the Production mode. I will look into it.

**Comment by musabibnusiraj** [comment]
Thank you for your kind reply.

### Working fine on release mode.

Building apk using the below commands.

`flutter build apk --no-shrink`

**or**

`flutter build apk --split-per-abi --no-shrink`

**Comment by nishalsehan** [comment]
Did this bug fix?
