### ISSUE TITLE
Switch to Production

### ISSUE THREAD

**Issue by musabibnusiraj** [SrilalS/Payhere-Flutter-Plugin#2]
Please put the sample code.
That how to switch sandbox to production.

**Comment by SrilalS** [comment]
Your OneTimePayment object has a method called "setProductionMode()". try setting that before executing the Payment.

**Comment by SrilalS** [comment]
It seems there is bug. Ill look into it. Thank you for pointing out.

**Comment by SrilalS** [comment]
@musabibnusiraj example,
OneTimePayment otp = OneTimePayment(.....

otp.setProductionMode();

Could you try this?

**Comment by musabibnusiraj** [comment]
![image](https://user-images.githubusercontent.com/47845204/92562871-4b433a00-f294-11ea-8edc-877a22b7ab88.png)

**Comment by SrilalS** [comment]
that should be placed Just before the line that executes the payment. For example, if you payhere object is ph,

otp.setProductionMode();
ph.makeOneTimePayment(otp);

**Comment by musabibnusiraj** [comment]
@SrilalS  Yeah. It's working fine.

```
onPressed: () async {
         otp.setProductionMode();
         String reps = await payhere.makeOneTimePayment(otp);
         setState(() {
                  response = reps;
         });
  }
```
