### ISSUE TITLE
Merchant ID is incorrect. Please contact your Merchant on this. error

### ISSUE THREAD

**Issue by nishalsehan** [SrilalS/Payhere-Flutter-Plugin#4]
PHResponse{status=-1, message='Merchant ID is incorrect. Please contact your Merchant on this.', data=null}

but merchant id is correct.

**Comment by SrilalS** [comment]
Have you added the application to the PayHere Console?

**Comment by nishalsehan** [comment]
Yeah i added the package name. how can I use sandbox merchant credentials?

**Comment by SrilalS** [comment]
You need to set the onetimepayment object to sandbox mode. 

For example myOTP.setSandBoxMode();

**Comment by nishalsehan** [comment]
thank you. it's working now.
